### ISSUE TITLE
Compresses and Decompress 

### ISSUE THREAD

**Issue by IAFahim** [SajidHShanta/image-compression#1]
Is the task was to:

```
Compress an image to zip
Decompress an image to zip
```

or

```
Compress an image to the image formats reducing the size. 
ex (image.png(2 MB), image.jpeg(3 MB) -> imageNew.png(200 KB), imageNew.jpeg)(320 KB)

Decompress an image to the image formats reducing the size. 
ex imageNew.png(200 KB), imageNew.jpeg)(320 KB)->(image.png(2 MB), image.jpeg(3 MB)
```

The confusion arise from this as searching for the topic yield different result (supporting the second topic that was asked for)

![image](https://user-images.githubusercontent.com/63500913/135033164-78ea8a1a-0e15-46dc-b4d8-ab229259ee74.png)
 
Farther from the topic of AI being asked for, it is possible and not required in post. 

![image](https://user-images.githubusercontent.com/63500913/135033478-fb53584d-14aa-406d-a479-334e332dcbd1.png)

**Comment by SajidHShanta** [comment]
Yes, @IAFahim you are right. I also got confused regarding this.
Besides the compress and decompress feature, also implemented resizing images feature [[refer to my 4th commit](https://github.com/SajidHShanta/image-compression/commit/53f12fbcfbffa75e200f990c743d72674158c493)].
